[tool.poetry]
name = "stripe-checkout"
version = "0.1.0"
description = ""
authors = ["Abhijeet"]

[tool.poetry.dependencies]
python = "^3.9"
stripe = "^2.71.0"
fastapi = "^0.75.1"
uvicorn = "^0.17.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
